### PR TITLE
New version

### PR DESCRIPTION
**Pull request by tristanlatr**
Hi,

Here is a proposed new version of the script.
The major changes is that we can now install the scraper with `pip` if you agree to publish it.
Then it creates a `kijiji` command, shortcut for main.py basically.
Also some options are configurable with CLI options, useful if we have several different searches to do.

### CODE REVIEW

**Comment by tristanlatr** [comment]
Oh and other thing, in order to be have `kijiji` command in the PATH, the database is now stored by default in ~/.kijiji_scraper/ads.json or %APPDATA%/.kijiji_scraper/ads.json on Windows.

Please try out the feature and let me know if it's ok to merge ! :)

**Comment by tristanlatr** [comment]
If you do not wish to publish it on PyPi , it's ok too. You can just remove the part regarding Pypi install in the readme

**Comment by CRutkowski** [comment]
Thanks for the work you put in on this! I quickly skimmed over the code and it looks good so far.
I'll test it out tonight and merge the PR if everything works.

**Comment by tristanlatr** [comment]
Great thanks.

May be I'll add a note about how to safely run several searches at the same time. The trick is to initiate a ads.json file in your current directory and assign as many ads.json files as searches config.

I currently have 4 processes of `kijiji` that runs into screens with their own ads.json file, different urls and emails.

If we leave several processes use the defaults file, it will cause concurrent accesses at some point as corrupt the json file.

**Comment by tristanlatr** [comment]
Also please tell me if your ok publishing the package on PyPi. Here is an example script to add in the project folder to publish rapidly.
```
#! /bin/bash 
python3 setup.py build check sdist bdist_wheel
twine upload --verbose dist/* 
python3 setup.py clean
rm -rf ./dist
rm -fr ./build
rm -fr ./kijiji_scraper.egg-info

```

**Comment by CRutkowski** [comment]
I'm going to try using [this package](https://pypi.org/project/sqlitedict/) to store the ads as it should solve the issue you mentioned with running multiple concurrent scripts.
I am also okay with publishing the package to PyPi and I will create a github action to do that.

**Comment by tristanlatr** [comment]
@CRutkowski yes it could work but having one specific file per searches is also useful. For exemple, friends are looking for appartements with différents criterial that overlaps sometimes . And I want to make sure everyone get the all ads emailed.

**Pull request merged**
